routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
// User
Route::group(['as' => 'client.', 'middleware' => ['auth' => 'verified']], function () {
    Route::get('home', 'HomeController@redirect');
    Route::get('dashboard', 'HomeController@index')->name('home');
    Route::get('change-password', 'ChangePasswordController@create')->name('password.create');
    Route::post('change-password', 'ChangePasswordController@update')->name('password.update');
    Route::get('test', 'TestsController@index')->name('test');
    Route::get('start_quiz/{id}', 'TestsController@startQuiz')->name('startQuiz');
    Route::get('get_questions/{category_id}', 'TestsController@getQuestions')->name('getQuestions');
    Route::post('test', 'TestsController@store')->name('test.store');
    Route::get('showall/{id}', 'HomeController@showAll')->name('showAll');
    Route::get('end/{id}', function ($id) {
        return view('client.end', compact('id'));
    });
    Route::get('results/{result_id}', 'ResultsController@show')->name('results.show');
    Route::get('send/{result_id}', 'ResultsController@send')->name('results.send');
});

Auth::routes(['verify' => true]);

// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth.admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

      // subcategories
      Route::get('subcategories/getspecificsubcategory','SubcategoriesController@getspecificsubcategory')->name('subcategories.getspecificsubcategory');
      Route::delete('subcategories/destroy', 'SubcategoriesController@massDestroy')->name('subcategories.massDestroy');
      Route::resource('subcategories', 'SubcategoriesController');
    // Questions
    Route::delete('questions/destroy', 'QuestionsController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions', 'QuestionsController');

    // Options
    Route::delete('options/destroy', 'OptionsController@massDestroy')->name('options.massDestroy');
    Route::resource('options', 'OptionsController');

    // Results
    Route::delete('results/destroy', 'ResultsController@massDestroy')->name('results.massDestroy');
    Route::resource('results', 'ResultsController');
});

resources/views/home.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    <div class="row" style="margin-bottom: 15px;">
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-info">
            <div class="inner">
              <h3>{{$total_categories}}</h3>

              <p>Categories</p>
            </div>
            <div class="icon">
              <i class="fas fa-gem"></i>
            </div>
            <a href="{{route('admin.categories.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-success">
            <div class="inner">
              <h3>{{$total_questions}}</h3>

              <p>Questions</p>
            </div>
            <div class="icon">
                <i class="ion ion-help"></i>
            </div>
            <a href="{{route('admin.questions.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-warning">
            <div class="inner">
              <h3>{{$total_users}}</h3>

              <p>User Registrations</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{{route('admin.users.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-danger">
            <div class="inner">
              <h3>{{$total_games}}</h3>

              <p>Games Played</p>
            </div>
            <div class="icon">
              <i class="fab fa-playstation"></i>
            </div>
            <a href="{{route('admin.results.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
      </div>

    <div class="row">
        <div class="col-lg-12">
            
            <div class="banner-item-wrapper">
                <div class="row">
                    <div class="col-md-12">
                        <!-- Bar chart -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <div class="box-body">
                                    <div style=""></div>
                                    <div id="bar"
                                        style="min-width: 310px; min-height: 400px; max-width: 1500px; max-height: 800px; margin: 0 auto"></div>
                                </div>
                            </div>
                            <!-- /.box-body-->
                        </div>
                        <!-- /.box -->
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
{{-- <script src="https://code.highcharts.com/modules/drilldown.js"></script> --}}

<script>
// Create the bar chart
            Highcharts.chart('bar', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Top Scorers'
                },            
                accessibility: {
                    announceNewData: {
                        enabled: true
                    }
                },
                xAxis: {
                    type: 'category'
                },
                yAxis: {
                    title: {
                        text: 'points'
                    }
        
                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    series: {
                        borderWidth: 0,
                        dataLabels: {
                            enabled: true,
                            format: '{point.y}'
                        }
                    }
                },
        
                tooltip: {
                    headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                    pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y} </b>points <br/>'
                },
        
                series: [
                    {
                        name: "Scores",
                        colorByPoint: true,
                        data: [ 
                                @foreach($results as $result) 
                                {name: "{{$result->user->name}}", y: {{$result->total}} },
                                @endforeach     
                             ]
                    }
                ],
                
            });
</script>
@endsection

resources/views/test.blade.php
<!DOCTYPE html>
<html>

<head>
    <style>
        .logo-wrapper {
	text-align: center;
	margin-bottom: -37px;
}

.logo {
	width: 100px;
	display: inline-block;
}

.navbar {
	li {
		display: inline-block;
		padding: 0 10px 10px;
	}
}

.half {
	width: 50%;
	display: block;
	float: left;
}

.right-navlist {
	padding-left: 60px;
}

.left-navlist {
	text-align: right;
	padding-right: 60px;
}
        </style>
</head>
<body>
<div class="container">
    <div class="navbar navbar-default">
		<div class="logo-wrapper">
			<div class="logo"><img class="logo" src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/logo_placeholder.png" alt=""></div>
		</div>
		<div class="half">		
			<ul class="left-navlist">
				<li>Home</li>
				<li>About</li>
			</ul>
		</div>
		<div class="half">		
			<ul class="right-navlist">
				<li>Contact</li>
				<li>Profile</li>
				<li>Maps</li>
			</ul>
		</div>
    </div>
   
    <div class="jumbotron">
        <h1>Twitter Bootstrap 3.0</h1>
        <p class="lead">Starter template with CSS and JS included.</p>
        <p><a class="btn btn-lg btn-primary" href="#fork">Fork this fiddle</a></p>
      </div>
</div>
</body>
</html>