routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
// User
Route::group(['as' => 'client.', 'middleware' => ['auth' => 'verified']], function () {
    Route::get('home', 'HomeController@redirect');
    Route::get('dashboard', 'HomeController@index')->name('home');
    Route::get('change-password', 'ChangePasswordController@create')->name('password.create');
    Route::post('change-password', 'ChangePasswordController@update')->name('password.update');
    Route::get('test', 'TestsController@index')->name('test');
    Route::get('start_quiz/{id}', 'TestsController@startQuiz')->name('startQuiz');
    Route::get('get_questions/{category_id}', 'TestsController@getQuestions')->name('getQuestions');
    Route::post('test', 'TestsController@store')->name('test.store');
    Route::get('showall/{id}', 'HomeController@showAll')->name('showAll');
    Route::get('end/{id}', function ($id) {
        return view('client.end', compact('id'));
    });
    Route::get('results/{result_id}', 'ResultsController@show')->name('results.show');
    Route::get('send/{result_id}', 'ResultsController@send')->name('results.send');
});

Auth::routes(['verify' => true]);

// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth.admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

      // subcategories
      Route::get('subcategories/getspecificsubcategory','SubcategoriesController@getspecificsubcategory')->name('subcategories.getspecificsubcategory');
      Route::delete('subcategories/destroy', 'SubcategoriesController@massDestroy')->name('subcategories.massDestroy');
      Route::resource('subcategories', 'SubcategoriesController');
    // Questions
    Route::delete('questions/destroy', 'QuestionsController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions', 'QuestionsController');

    // Options
    Route::delete('options/destroy', 'OptionsController@massDestroy')->name('options.massDestroy');
    Route::resource('options', 'OptionsController');

    // Results
    Route::delete('results/destroy', 'ResultsController@massDestroy')->name('results.massDestroy');
    Route::resource('results', 'ResultsController');
});

resources/views/client/category.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Quick Quiz - Play</title>
    <link rel="stylesheet" href="{{ asset('css/quiz/category.css')}}" />
    {{-- <link rel="stylesheet" href="{{ asset('css/app.css')}}" /> --}}
  </head>
  <body>
    <div class="container">
        @foreach($categories as $category)
            <div class="bg1" onclick="getQuestions({{$category->id}})">
            <h2>{{$category->name}}</h2>
            {{-- <p>Goals Completed</p> --}}
            </div>
        @endforeach
    {{-- <div class="bg1">
      <h2><i class="fas fa-battery-three-quarters"></i></h2>
      <p>Respiration</p>
    </div>
    <div class="bg2">
      <h2><i class="fas fa-running"></i></h2>
      <p>Miles</p>
    </div>
    <div class="bg1">
      <h2>36 &deg;</h2>
      <p>Temperature</p>
    </div>
    <div class="bg1">
      <h2><i class="fas fa-bed"></i></h2>
      <p>Sleep Keep</p>
    </div>
    <div class="bg2">
      <h2>98 <span>bpm</span></h2>
      <p>Heart Rate</p>
    </div>
    <div class="bg1">
      <h2>170 <span>lbs</span></h2>
      <p>Weight</p>
    </div>
    <div class="bg1">
      <h2>28 <span>%</span></h2>
      <p>Fat Percentage</p>
    </div>
    <div class="bg2">
      <h2>118 <span>mgdl</span></h2>
      <p>Blood Glucose</p>
    </div>
    <div class="bg2">
      <h2>680 <span>kcal</span></h2>
      <p>AVG Consumption</p>
    </div>
    <div class="bg2">
      <h2><i class="fas fa-dumbbell"></i></h2>
      <p>Workouts</p>
    </div>
    <div class="bg2">
      <h2>85 <span>%</span></h2>
      <p>Body Hydration</p>
    </div> --}}
  </div>
  <script>
    function getQuestions(id){
        const category_id = id;
        return window.location.assign("/start_quiz/"+ category_id);
      }
  </script>
  </body>
</html>

resources/views/client/changePassword.blade.php
@extends('layouts.client')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Change password') }}</div>

                <div class="card-body">
                    @if(session('status'))
                        <div class="row">
                            <div class="col-12">
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            </div>
                        </div>
                    @endif

                    <form method="POST" action="{{ route('client.password.update') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required autocomplete="new-password">

                                @if($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Change password') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/client/end.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Congrats!</title>
    <link rel="stylesheet" href="{{ asset('/css/quiz/app.css')}}" />
  </head>
  <body>
    <div class="container">
      <div id="end" class="flex-center flex-column">
        <h3> Final Score </h3>
        <h1 id="finalScore"></h1>
        
        <a class="btn" href="{{route('client.startQuiz', $id)}}">Play Again</a>
        <a class="btn" href="{{route('client.home')}}">Go Home</a>
      </div>
    </div>
    <script src="{{ asset('/js/end.js')}}"></script>
  </body>
</html>

resources/views/client/home.blade.php
@extends('layouts.client')

@include('partials.client.head')


@section('content')
<div class="container">    
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="col-lg-12 row performance" style="margin: 15px 0px;">
                <div class="col-lg-3 col-6">
                      <div class="user-activity">{{$total_score = auth()->user()->userResults()->sum('total_points')}}  <br>  Total Score</div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                        <div class="user-activity">{{ round(($total_score / ($attempted * 5))*10, 2)}} / 10 <br>  Average Score</div>  
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                        <div class="user-activity">{{auth()->user()->userResults()->count()}} <br> Quizes Played</div>  
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <div class="user-activity">{{$attempted}} <br> Questions Faced</div>  
                </div>
                <!-- ./col -->
              </div>
        <hr style="border:1px solid #2C5364;">

            @foreach($categories as $key=>$category)
            <div class="col-md-12" style="padding: 15px 15px;">
                @foreach($category as $subcategory)
                    <h3>{{$subcategory->category->name}}</h3>
                    @if ($categoy[$key]->last_page > 1)
                        <a href="{{url('showall',$subcategory->category->id)}}" class="showall float-right" > see more </a>
                    @endif
               
                    @break
                    @endforeach
                <div class="row flex-container">
                    @foreach($category as $subcategory)
                        <div class="sub-category" onclick="getQuestions({{$subcategory->id}})">{{$subcategory->name}}</div>
                    @endforeach
                </div>
            </div>
            @endforeach
        </div>

        <div class="col-md-2">
            <div class="card" style="padding: 10px;">
            <h6> Total Participants : <strong> {{$total_users}} </strong></h6>
            <hr style="border:1px solid #2C5364;">
            <h6>Top 10 Scorers:</h6>
                @foreach($results as $result)
                    <small class="pull-left" style="margin:5px 0px; border:1px solid #2C5364; border-radius:5px; padding:2px; font-size:15px;">{{$result->user->name}} : <strong>{{$result->total}}</strong> </small>
                @endforeach
            </div>
        </div>
    </div>
</div>

@include('partials.client.footer')
@endsection

resources/views/client/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Test No. {{ $result->id }}</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
        <style type="text/css">
            html {
                margin: 0;
            }
            body {
                background-color: #FFFFFF;
                font-size: 10px;
                margin: 36pt;
            }
        </style>
    </head>
    <body>
        <p class="mt-5">Total points: {{ $result->total_points }} points</p>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Question Text</th>
                    <th>Points</th>
                </tr>
            </thead>
            <tbody>
                @foreach($result->questions as $question)
                    <tr>
                        <td>{{ $question->question_text }}</td>
                        <td>{{ $question->pivot->points }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </body>
</html>

resources/views/client/results.blade.php
@extends('layouts.client')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Results of your test</div>

                <div class="card-body">
                    @if(session('status'))
                        <div class="row">
                            <div class="col-12">
                                <div class="alert alert-success" role="alert">
                                    <p>{{ session('status') }}</p>

                                    <a href="{{ route('client.test') }}" class="btn btn-primary">Start test again</a>
                                </div>
                            </div>
                        </div>
                    @endif

                    <p>Total points: {{ $result->total_points }} points</p>

                    <a href="{{ route('client.results.send', $result->id) }}" class="btn btn-primary">GET DETAILS IN PDF BY EMAIL</a>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/client/subcategory.blade.php
@extends('layouts.client')
@include('partials.client.head')

@section('content')
<div class="container">
   <p> Popular categories under <strong>{{$category->name}}</strong> </p>
        <hr style="border:1px solid #203A43;">
        <div class="row flex-container">
            @foreach ($category->subcategories as $subcategory)
                <div class="sub-category" style="min-width: 10em; min-height:9em;" onclick="getQuestions({{$subcategory->id}})">{{$subcategory->name}}</div>
            @endforeach
        </div>
</div>

@include('partials.client.footer')
@endsection

resources/views/client/test.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Quick Quiz - Play</title>
    <link rel="stylesheet" href="{{ asset('css/quiz/app.css')}}" />
    <link rel="stylesheet" href="{{ asset('css/quiz/game.css')}}" />
  </head>
  <body>
    <div class="container">
      <div id="loader"></div>
        <div id="game" class="justify-center flex-column hidden">
      <div id="hud">
          <div id="hud-item">
            <p id="progressText" class="hud-prefix">
              Question
            </p>
            <div id="progressBar">
              <div id="progressBarFull"></div>
            </div>
          </div>
          <div id="hud-item">
            <p class="hud-prefix">
              Score
            </p>
            <h1 class="hud-main-text" id="score">
              0
            </h1>
          </div>
        </div>
        <h2 id="question"></h2>
        <div class="choice-container">
          <p class="choice-prefix">A</p>
          <p class="choice-text" data-number="1"></p>
        </div>
        <div class="choice-container">
          <p class="choice-prefix">B</p>
          <p class="choice-text" data-number="2"></p>
        </div>
        <div class="choice-container">
          <p class="choice-prefix">C</p>
          <p class="choice-text" data-number="3"></p>
        </div>
        <div class="choice-container">
          <p class="choice-prefix">D</p>
          <p class="choice-text" data-number="4"></p>
        </div>
      </div>
    </div>
    <script type="text/javascript">var category_id = <?php echo $id; ?></script>
    <script src="{{ asset('js/jquery/jquery.min.js')}}"></script>
    <script src="{{ asset('js/game.js')}}"></script>
  </body>
</html>